### ISSUE TITLE
[Correcao] podemos criar infográficos sobre a jornada do engenheiro de software?

### ISSUE THREAD

**Issue by ghost** [codermarcos/jornada-engenheiro-de-software#2]
### Como chegou aqui?

Encontrei um link no meio do conteúdo que me mandou aqui!

### Como quer ajudar?

Achei um erro no conteúdo

### Descreva qual o problema, ou como ajudar

podemos criar infográficos sobre a jornada do engenheiro de software?

estou pensando em ajudar e penso em criar infográficos para transformar arquivos em markdown em imagens ilustrativas, e distribuir essas imagens ilustrativas em grupos do telegram, whatsapp e por aí. 

para que as pessoas tenham maior consciência em desenvolver e manter ou gerenciar bons softwares. ou para conhecer esse projeto maravilhoso

**Comment by codermarcos** [comment]
Cara fica a vontade pode abrir uma PR aqui! E Também fique 100% a vontade em adicionar conteúdo!
💘 Obrigado novamente pelas contribuições!
